Add 'take' and 'skip' functions to reader
spatie/simple-excel pull request #35
Opened 2020-10-03 22:30 UTC by ahallhognason

Closes #34 

Instead of `offset` and `limit`, I used `take` and `skip` to follow the conventions from LazyCollections.

2020-10-04 17:48 UTC, freekmurze requested changes
Could you add an example to the readme?

2020-10-04 17:48 UTC, freekmurze commented on src/SimpleExcelReader.php
> +    private $skip = 0;
Typehint all properties

2020-10-04 17:48 UTC, freekmurze commented on src/SimpleExcelReader.php
> +    private $use_limit = false;
Use camelCase

2020-10-04 17:48 UTC, freekmurze commented on src/SimpleExcelReader.php
> +    public function take($count)
Add type hint and return type hint

2020-10-04 18:44 UTC, ahallhognason reviewed
Made all suggested changes.

2020-10-04 19:01 UTC, merged

2020-10-04 19:01 UTC, freekmurze commented
Thanks!

2020-10-05 08:27 UTC, thijsw commented
@ahallhognason Thank you for this PR, much welcomed!

2020-10-07 20:53 UTC, Francismori7 commented
This PR broke `getRows()`, if called multiple times one after the other on the same file instance. See #36

2020-10-07 21:28 UTC, freekmurze commented
@Francismori7 Could you send a PR for this fix. Also maybe add a test, so we don't encounter this regression again.