Add option to convert headers to snake_case format.
spatie/simple-excel pull request #49
Opened 2020-12-29 11:38 UTC by bruno-fernandes

This PR adds a new method that allows the conversion of headers to snake_case format.

```csv
Email,First Name,Last Name
john@example.com,john,doe
mary-jane@example.com,mary jane,doe
```

```php
$rows = SimpleExcelReader::create($pathToCsv)
    ->headersToSnakeCase()
    ->getRows()
    ->each(function(array $rowProperties) {
        // rowProperties converted to snake_case
        // ['email' => 'john@example', 'first_name' => 'John', 'last_name' => 'doe']
});
```

Laravel Excel 2 automatically converts all the headers to snake_case and I wanted to keep the same behaviour so users don't have to update any of the import templates. I am currently migrating to Simple Excel as I didn't like the latest version of Laravel Excel (too much boilerplate for simple tasks). Hope this can be helpful for others in the same situation.

2020-12-29 11:44 UTC, freekmurze requested changes
Thank you for this PR.

I like the functionality, but I think we can make it more flexible.

Let's add a function `convertHeaders` that accepts a callable. This callable gets each of titles and should give back the converted version.

Internally, `headersToSnakeCase` calls `convertHeaders` giving a callable that will do the conversion to snake case.

2020-12-29 11:44 UTC, freekmurze commented on src/SimpleExcelReader.php
> +                return str_replace(
Add a dedicated function called `toSnakeCase` for this.

2020-12-29 13:09 UTC, bruno-fernandes commented
@freekmurze done. Have also changed the trim option to call the convertHeaders method and extracted it to a dedicated method. A bit cleaner.

2020-12-29 13:22 UTC, freekmurze commented
Nice, the only thing missing now is an example of how to use `convertHeaders`. Could you add that to the readme? Thanks!

2020-12-29 13:45 UTC, bruno-fernandes commented
```convertHeaders``` method is protected. Not sure what kind of example to add.
Perhaps we should refactor to allow users to pass custom callbacks? The method is called from the ```processHeaderRow``` method based on the flags that have been set.

2020-12-29 14:00 UTC, freekmurze commented
> Perhaps we should refactor to allow users to pass custom callbacks?

Yup!

2020-12-29 21:22 UTC, bruno-fernandes commented
Done. Not sure about the naming... Feel free to give suggestions. :)

2020-12-30 09:26 UTC, freekmurze commented
Very nice, I'll pull this in and polish it a little bit before releasing 👍 

Thanks!

2020-12-30 09:26 UTC, merged