getHeaders()
spatie/simple-excel pull request #52
Opened 2021-01-16 19:28 UTC by AdamGaskins

PR for #51.

Love this package, and thanks for all the value you've added to the community (Laravel Beyond Crud has had a huge impact on our company 🙌🏻 ).

2021-01-17 15:02 UTC, freekmurze requested changes
Let's make the code a bit simpler!

2021-01-18 01:18 UTC, AdamGaskins commented
My understanding is the spreadsheet needs to be opened and the headers processed *after* any of the fluent methods are called (`useDelimiter()`, `trimHeaderRow()` etc.) but *before* either of `getRows()` or `getHeaders()` is called (e.g. we have a page on our site that opens the spreadsheet solely to read the headers for mapping purposes). Extracting this processing to its own method seemed to make the most sense to me, and also avoided `getHeaders()` needing to rewind the iterator. Let me know your thoughts!

2021-01-18 07:26 UTC, freekmurze commented
I think the clearest things to do, would be to have `getHeaders` to open the file and have it's own iterator independent of the `getRows` function. This would you won't need to keep a boolean tracking whether things have been processed or not.

I really don't mind that the file is opened twice, the performance impact will probably be negligible. Typing this message likely takes more time 🙂

2021-01-18 22:14 UTC, freekmurze requested changes

2021-01-18 22:14 UTC, freekmurze commented on src/SimpleExcelReader.php
> +        if ($this->processHeader && ! $this->headers) {
There's a big piece of indented code here. I can be simplified by first checking if headers is set to something. If it is, we can already return the headers.

2021-01-18 22:33 UTC, merged

2021-01-18 22:33 UTC, freekmurze commented
Thank you!

2021-03-18 11:28 UTC, avdb commented
Is there a reason why $reader is created in the getHeaders()?
I think you cannot set the delimiter for csv files how it's now implemented but maybe I'm missing something!